### ISSUE TITLE
Cannot reproduce the result in the paper

### ISSUE THREAD

**Issue by ye002** [csqiangwen/Deep-Unsupervised-Pixelization#2]
Thank you for the nice work. I ran the code but cannot get the similar result shown in the paper. Although I used the default parameters and trained the model for 150 epochs, is there any problem? and should I tune any parameters? Would it be possible to release the pre-trained model? 

![res](https://user-images.githubusercontent.com/45482304/53381315-bb8cb200-39b3-11e9-8d92-3cbbfe318a96.jpg)

**Comment by csqiangwen** [comment]
Thanks for your interest in our work. We could not release the pre-trained model as it is using in a commercial software. But I could give some advice in training: 1. Sometimes, the best performance epoch number is not constant, you can try more epochs to obtain the best results; 2. For each pixelized image, the 'fake_B_x4_processed' is always the best and the other two are too hard to train if you do not want to train too much epochs; 3. Add more portrait images in the training dataset; 4. Using the data augmentation strategy is always a good way to improve the model performance.

**Comment by ye002** [comment]
Thanks for your quick reply. I 'll try it.
